shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 5
  - npm install
build: off
test_script: npm run-script test-only
cache:
  - bower_components
  - node_modules
  - 'C:\Users\appveyor\AppData\Roaming\npm\node_modules'
